language: julia

os:
  - linux
julia:
  - 1.3.0
addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib
      - python3-pip
before_install:
  - python3 -m pip install awkward
  - python3 -m pip install uproot 
env:
  matrix:
    - PYTHON=python3

jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; 
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();'
        - julia --project=docs/ docs/make.jl
        - julia -e 'using Pkg; Pkg.test(coverage=true);'

after_success:
  - julia -e 'using Pkg;
              Pkg.add("Coverage");
              using Coverage;
              Codecov.submit(process_folder());'
